name: food_tech_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Actor
      fonts:
        - asset: assets/fonts/Actor-Regular.ttf

    - family: Allerta
      fonts:
        - asset: assets/fonts/Allerta-Regular.ttf

    - family: MoreSugar
      fonts:
        - asset: assets/fonts/MoreSugar-Regular.ttf

  assets:
    - assets/img/logo_rico_app.png
    - assets/img/icono_rico_app.png
    - assets/img/entrada.png
    - assets/img/comida.png
    - assets/img/postre.png
    - assets/img/bebida.png
    - assets/img/producto.png
    - assets/img/producto1.png
    - assets/img/imaproducto.png    
    - assets/img/compra.png





