name: food_tech_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Actor
      fonts:
        - asset: assets/fonts/Actor-Regular.ttf

    - family: Allerta
      fonts:
        - asset: assets/fonts/Allerta-Regular.ttf

    - family: MoreSugar
      fonts:
        - asset: assets/fonts/MoreSugar-Regular.ttf

  assets:
    - assets/img/





