// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs58GK916Jz9ijBD_nxO39bE2lUT3lCmQ',
    appId: '1:4987066063:web:ebaae1aec15227993849ba',
    messagingSenderId: '4987066063',
    projectId: 'dbrickoapp',
    authDomain: 'dbrickoapp.firebaseapp.com',
    storageBucket: 'dbrickoapp.appspot.com',
    measurementId: 'G-412DDT1K5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrFCLEym_IjJeez7DnschiLjUsC-J0TQ',
    appId: '1:4987066063:android:0c8ed2ae3be16d8a3849ba',
    messagingSenderId: '4987066063',
    projectId: 'dbrickoapp',
    storageBucket: 'dbrickoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJP6rx_zdXOaZNOASwhmCe_IXcW_2TGG0',
    appId: '1:4987066063:ios:4bde64e4eb63991d3849ba',
    messagingSenderId: '4987066063',
    projectId: 'dbrickoapp',
    storageBucket: 'dbrickoapp.appspot.com',
    iosBundleId: 'com.example.foodTechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJP6rx_zdXOaZNOASwhmCe_IXcW_2TGG0',
    appId: '1:4987066063:ios:4bde64e4eb63991d3849ba',
    messagingSenderId: '4987066063',
    projectId: 'dbrickoapp',
    storageBucket: 'dbrickoapp.appspot.com',
    iosBundleId: 'com.example.foodTechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs58GK916Jz9ijBD_nxO39bE2lUT3lCmQ',
    appId: '1:4987066063:web:f726f0f5fc694c3c3849ba',
    messagingSenderId: '4987066063',
    projectId: 'dbrickoapp',
    authDomain: 'dbrickoapp.firebaseapp.com',
    storageBucket: 'dbrickoapp.appspot.com',
    measurementId: 'G-EY9JNY7W6T',
  );
}
